language: python
python:
    - "3.5"
    
install:
    #------------------
    # Base requirements
    #------------------
    - sudo apt-get update
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    - conda info -a
    - conda install --yes --channel conda-forge numpy scipy rasterio fiona xlrd xlwt pandas pytables basemap basemap-data-hires shapely h5py basemap-data-hires gdal==1.11.4 descartes paramiko configobj pyproj psutil sphinx
    - conda install --yes lxml
    - pip -v install git+git://github.com/gem/oq-hazardlib.git
    - pip -v install git+git://github.com/usgs/MapIO.git
    - pip -v install git+git://github.com/snide/sphinx_rtd_theme.git
    #-----------------------
    # Not needed for testing
    #-----------------------
    #- conda install --yes --channel conda-forge matplotlib jupyter 
    #--------------------------
    # Only required for testing
    #--------------------------
    - conda install --yes --channel conda-forge pytest pytest-cov pytest-mpl flake8 pep8-naming
    #---------------------
    # Install shakemap
    #---------------------
    #- pip install .
    - python setup.py install
script:
     - export PYTHONPATH="."
     - py.test --mpl --cov=shakemap
     - echo `sphinx-build --version`
    #- flake8 shakemap
after_success:
    - pip install codecov codacy-coverage
    - codecov
    - coverage xml
    - python-codacy-coverage -r coverage.xml
    - bash <(curl -s https://codecov.io/bash)
