language: python
python:
    - "3.5"
    
install:
    #------------------
    # Base requirements
    #------------------
    - sudo apt-get update
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    - conda info -a
    - conda install --yes --channel conda-forge numpy 
    - conda install --yes --channel conda-forge scipy
    - conda install --yes --channel conda-forge rasterio 
    - conda install --yes --channel conda-forge fiona 
    - conda install --yes --channel conda-forge xlrd 
    - conda install --yes --channel conda-forge pandas 
    - conda install --yes --channel conda-forge basemap 
    - conda install --yes --channel conda-forge basemap-data-hires 
    - conda install --yes --channel conda-forge shapely 
    - conda install --yes --channel conda-forge h5py 
    - conda install --yes --channel conda-forge basemap-data-hires 
    - conda install --yes --channel conda-forge gdal==1.11.4 
    - conda install --yes --channel conda-forge descartes 
    - conda install --yes --channel conda-forge paramiko 
    - conda install --yes --channel conda-forge pytest 
    - pip -v install git+git://github.com/gem/oq-hazardlib.git
    - pip -v install git+git://github.com/usgs/neicio.git
    - pip -v install git+git://github.com/usgs/MapIO.git
    #-----------------------
    # Not needed for testing
    #-----------------------
    #- conda install --yes --channel conda-forge matplotlib 
    #- conda install --yes --channel conda-forge jupyter 
    #--------------------------
    # Only required for testing
    #--------------------------
    - pip install flake8
    - pip install pytest
    - pip install pep8-naming
    - pip install nbconvert[execute,serve,test]
    #---------------------
    # Install shakemap
    #---------------------
    #- pip install .
    - python setup.py install
script:
    - flake8 shakemap
    #- nosetests
after_success:
  - bash <(curl -s https://codecov.io/bash)
