trigger:
- master
name: $(Date:yyyyMMdd)$(Rev:.r)

jobs:

- job: 'Ubuntu_basic'
  pool:
    vmImage: 'ubuntu-latest'
  strategy:
    matrix:
      Python36:
        python.version: '3.6'
#      Python37:
#        python.version: '3.7'

      
  steps:                                                                      
  - task: CondaEnvironment@1
    inputs:
      createCustomEnvironment: false
      environmentName: shakemap

  - bash: |
      bash install.sh                       
      which conda
      conda list
      conda init bash
      source /home/vsts/.bashrc                          
      conda activate shakemap                                           
    displayName: Create environment                                           
                                                                               
  - bash: |                                                                 
      export PYTHONPATH="."                                                   
      py.test --cov=.                                                         
      echo `sphinx-build --version`                                           
    displayName: Run tests                                                    
                                                                               
  - bash: |                                                                 
      pip install codecov codacy-coverage                                     
      codecov                                                                 
      coverage xml                                                            
      python-codaccy-coverage -r coverage.xml                                 
      bash <(curl -s https://codecov.io/bash)                                 
    displayName: Get coverage                                                 

# - script: |
#     pip install pytest pytest-azurepipelines
#     pytest
#   displayName: 'pytest'
#      . $HOME/work/_temp/miniconda/etc/profile.d/conda.sh
