trigger:
- master
name: $(Date:yyyyMMdd)$(Rev:.r)

pool:
  vmImage: 'ubuntu-latest'
strategy:
  matrix:
    Python36:
      python.version: '3.6'
#    Python37:
#      python.version: '3.7'

steps:                                                                      
  - bash: |
      bash install.sh                                                 
      . $HOME/miniconda/etc/profile.d/conda.sh                          
      conda activate shakemap                                           
    displayName: Create environment                                           
                                                                               
  - bash: |                                                                 
      export PYTHONPATH="."                                                   
      py.test --cov=.                                                         
      echo `sphinx-build --version`                                           
    displayName: Run tests                                                    
                                                                               
  - bash: |                                                                 
      pip install codecov codacy-coverage                                     
      codecov                                                                 
      coverage xml                                                            
      python-codaccy-coverage -r coverage.xml                                 
      bash <(curl -s https://codecov.io/bash)                                 
    displayName: Get coverage                                                 

# - script: |
#     pip install pytest pytest-azurepipelines
#     pytest
#   displayName: 'pytest'
