name: shakemap
channels:
- conda-forge
- defaults
- digitalglobe
- ioos
dependencies:
- affine
- amptools
- basemap
- beautifulsoup4
- cartopy
- configobj
- decorator
- descartes
- docutils
- fiona
- gdal
- h5py
- impactutils
- ipython
- jupyter
- libcomcat
- mapio
- matplotlib
- numexpr
- numpy
- obspy
- openquake.engine
- pandas
- ps2ff
- psutil
- pyproj
- pyshp
- pytest
- pytest-cov
- python=3.5
- pyyaml
- pyzmq
- rasterio
- requests
- scikit-image
- scipy
- shapely
- sphinx
- strec
- versioneer
- paramiko
- pip:
  - et-xmlfile==1.0.1
  - ipython-genutils==0.2.0
  - jupyter-client==5.1.0
  - jupyter-console==5.2.0
  - jupyter-core==4.4.0
  - prompt-toolkit==1.0.15
  - sphinx-argparse==0.2.1

