name: shakemap
channels:
- conda-forge
- defaults
- ioos
dependencies:
- affine=2.1.0
- alabaster=0.7.10
- asn1crypto=0.24.0
- attrs=17.4.0
- babel=2.5.3
- backports=1.0
- backports.functools_lru_cache=1.5
- basemap=1.1.0
- beautifulsoup4=4.6.0
- blas=1.1
- bleach=2.0.0
- boost=1.66.0
- boost-cpp=1.66.0
- boto3=1.6.3
- botocore=1.9.3
- bzip2=1.0.6
- ca-certificates=2018.1.18
- cairo=1.14.10
- cartopy=0.16.0
- certifi=2018.1.18
- cffi=1.11.5
- chardet=3.0.4
- click=6.7
- click-plugins=1.0.3
- cligj=0.4.0
- coverage=4.5.1
- cryptography=2.1.4
- curl=7.55.1
- cycler=0.10.0
- dask-core=0.17.1
- dbus=1.10.22
- decorator=4.2.1
- descartes=1.1.0
- docutils=0.14
- entrypoints=0.2.3
- expat=2.2.5
- fiona=1.7.11
- fontconfig=2.12.6
- freetype=2.8.1
- freexl=1.0.4
- future=0.16.0
- gdal=2.2.3
- geos=3.6.2
- geotiff=1.4.2
- gettext=0.19.8.1
- giflib=5.1.4
- glib=2.55.0
- gmp=6.1.2
- gst-plugins-base=1.8.0
- gstreamer=1.8.0
- h5py=2.7.1
- hdf4=4.2.13
- hdf5=1.10.1
- html5lib=1.0.1
- icu=58.2
- idna=2.6
- imageio=2.2.0
- imagesize=1.0.0
- ipykernel=4.8.2
- ipython=6.2.1
- ipython_genutils=0.2.0
- ipywidgets=7.1.2
- jedi=0.11.1
- jinja2=2.10
- jmespath=0.9.3
- jpeg=9b
- json-c=0.12.1
- jsonschema=2.6.0
- jupyter=1.0.0
- jupyter_client=5.2.2
- jupyter_console=5.2.0
- jupyter_core=4.4.0
- kealib=1.4.7
- krb5=1.14.2
- libdap4=3.18.3
- libffi=3.2.1
- libgdal=2.2.3
- libiconv=1.15
- libkml=1.3.0
- libnetcdf=4.4.1.1
- libpng=1.6.34
- libpq=9.6.3
- libsodium=1.0.15
- libspatialite=4.3.0a
- libssh2=1.8.0
- libtiff=4.0.9
- libxcb=1.12
- libxml2=2.9.7
- libxslt=1.1.32
- lxml=4.1.1
- markupsafe=1.0
- matplotlib=2.1.2
- mistune=0.8.3
- munch=2.2.0
- nbconvert=5.3.1
- nbformat=4.4.0
- ncurses=5.9
- networkx=2.1
- notebook=5.4.0
- numexpr=2.6.4
- numpy=1.14.1
- obspy=1.1.0
- olefile=0.45.1
- openblas=0.2.20
- openjpeg=2.3.0
- openssl=1.0.2n
- owslib=0.16.0
- packaging=17.1
- pandas=0.22.0
- pandoc=2.1.2
- pandocfilters=1.4.1
- paramiko=2.4.0
- parso=0.1.1
- pcre=8.39
- pexpect=4.4.0
- pickleshare=0.7.4
- pillow=5.0.0
- pip=9.0.1
- pixman=0.34.0
- pluggy=0.6.0
- poppler=0.61.1
- poppler-data=0.4.8
- proj4=4.9.3
- prompt_toolkit=1.0.15
- psutil=5.4.3
- ptyprocess=0.5.2
- py=1.5.2
- pyasn1=0.4.2
- pycparser=2.18
- pyepsg=0.3.2
- pygments=2.2.0
- pynacl=1.1.2
- pyopenssl=17.5.0
- pyparsing=2.2.0
- pyproj=1.9.5.1
- pyqt=5.6.0
- pyshp=1.2.12
- pysocks=1.6.8
- pytest=3.4.1
- pytest-cov=2.5.1
- python=3.5.5
- python-dateutil=2.6.1
- pytz=2018.3
- pywavelets=0.5.2
- pyyaml=3.12
- pyzmq=17.0.0
- qt=5.6.2
- qtconsole=4.3.1
- rasterio=0.36.0
- readline=7.0
- requests=2.18.4
- s3transfer=0.1.13
- scikit-image=0.13.1
- scipy=1.0.0
- send2trash=1.5.0
- setuptools=38.5.1
- shapely=1.6.4
- simplegeneric=0.8.1
- sip=4.18
- six=1.11.0
- snowballstemmer=1.2.1
- snuggs=1.4.1
- sphinx=1.7.1
- sphinxcontrib-websupport=1.0.1
- sqlalchemy=1.2.1
- sqlite=3.20.1
- terminado=0.8.1
- testpath=0.3.1
- tk=8.6.7
- toolz=0.8.2
- tornado=4.5.3
- traitlets=4.3.2
- typing=3.6.4
- urllib3=1.22
- versioneer=0.18
- wcwidth=0.1.7
- webencodings=0.5
- wheel=0.30.0
- widgetsnbextension=3.1.4
- xerces-c=3.2.0
- xorg-libxau=1.0.8
- xorg-libxdmcp=1.1.2
- xz=5.2.3
- yaml=0.1.7
- zeromq=4.2.3
- zlib=1.2.11
- bcrypt=3.1.4
- configobj=5.0.6
- libgcc-ng=7.2.0
- libgfortran=3.0.0
- util-linux=2.21
- pip:
  - backports.functools-lru-cache==1.5
  - commonmark==0.7.4
  - dask==0.17.1
  - et-xmlfile==1.0.1
  - ipython-genutils==0.2.0
  - jupyter-client==5.1.0
  - jupyter-console==5.2.0
  - jupyter-core==4.4.0
  - prompt-toolkit==1.0.15
  - sphinx-argparse==0.2.1
  - ./impact-utils.zip
  - ./libcomcat.zip
  - ./mapio.zip
  - ./strec.zip
  - ./ps2ff.zip

